In [136]:
from scipy.io.wavfile import read
import numpy as np
import soundfile as sf
import sounddevice as sd
import random


data, fs = sf.read('dog.wav', dtype='int16')  
print(fs)
sd.play(data)

44100


In [137]:
N = len(data)
print(N)

71571


In [138]:
data

array([[-44, -37],
       [-45, -39],
       [-46, -43],
       ...,
       [  0,   1],
       [  0,   2],
       [  0,   0]], dtype=int16)

In [139]:
data.reshape(23857,6)

array([[-44, -37, -45, -39, -46, -43],
       [-44, -42, -46, -45, -47, -42],
       [-44, -37, -42, -31, -40, -25],
       ...,
       [  0,  -2,   2,  -3,   0,   0],
       [  0,  -2,  -1,  -2,   0,   2],
       [  0,   1,   0,   2,   0,   0]], dtype=int16)

In [140]:
data[0]

array([-44, -37], dtype=int16)

In [141]:
data[2][0]

-46

In [142]:
data = np.vectorize(np.binary_repr)(data, 12)

In [143]:
'''
for i in range (N):
    data[i][0] = random.randint(-50,100)
    data[i][1] = random.randint(0,100)
'''
data

array([['111111010100', '111111011011'],
       ['111111010011', '111111011001'],
       ['111111010010', '111111010101'],
       ...,
       ['000000000000', '000000000001'],
       ['000000000000', '000000000010'],
       ['000000000000', '000000000000']], dtype='<U16')

In [160]:
#for i in range(N):
#print [s.replace('00' , 'A') for s in data]
import numpy.core.defchararray as np_f
new_data = np_f.replace(data, '00', 'A')
new_data = np_f.replace(new_data, '11', 'T')
new_data = np_f.replace(new_data, '01', 'G')
new_data = np_f.replace(new_data, '10', 'C')
new_data

array([['TTTGGA', 'TTT0T0T'],
       ['TTTGAT', 'TTT0TA1'],
       ['TTTGAC', 'TTTGGG'],
       ...,
       ['AAAAAA', 'AAAAAG'],
       ['AAAAAA', 'AAAAAC'],
       ['AAAAAA', 'AAAAAA']], dtype='<U10')

In [151]:
for i in range (N):
    '''data[i][0] = random.randint(-50,100)
    data[i][1] = random.randint(0,100)'''
    
    #data[i][1] = 0
   # data[i][1] = 
    

In [148]:
for i in range(15000):
    print(data[i])

            

['111111010100' '111111011011']
['111111010011' '111111011001']
['111111010010' '111111010101']
['111111010100' '111111010110']
['111111010010' '111111010011']
['111111010001' '111111010110']
['111111010100' '111111011011']
['111111010110' '111111100001']
['111111011000' '111111100111']
['111111011010' '111111101100']
['111111100001' '111111110011']
['111111100111' '111111111100']
['111111101001' '000000000000']
['111111101011' '000000001010']
['111111110001' '000000001111']
['111111110110' '000000010101']
['111111111010' '000000011110']
['000000000010' '000000100100']
['000000000111' '000000101001']
['000000001110' '000000110001']
['000000010100' '000000110110']
['000000011001' '000001000000']
['000000011100' '000001000100']
['000000100110' '000001001001']
['000000101111' '000001001111']
['000000110011' '000001010011']
['000000110011' '000001010010']
['000000110100' '000001001110']
['000000110110' '000001001000']
['000000110000' '000001000010']
['000000110010' '000000111001']
['000000

['111100001010' '111100011000']
['111011111011' '111100100001']
['111100000001' '111100110001']
['111011011101' '111100011000']
['111010110101' '111100001001']
['111010111111' '111100100111']
['111011011110' '111101010100']
['111011111001' '111110000010']
['111100001001' '111110100011']
['111100001110' '111110110100']
['111100111010' '111111100111']
['111110010101' '000000111010']
['111111010011' '000001101111']
['111111101100' '000010001111']
['000000011101' '000010110000']
['000001010011' '000011001111']
['000001111100' '000011101001']
['000010011101' '000100000100']
['000010111010' '000100010000']
['000011011111' '000100100111']
['000011101010' '000100101010']
['000010110001' '000011110101']
['000001111100' '000011001101']
['000010001100' '000011010010']
['000010000111' '000010111100']
['000001010001' '000010000111']
['000000100110' '000001011011']
['000000101101' '000001000010']
['000000110110' '000000110010']
['000001001101' '000000101000']
['000001100101' '000000010011']
['000001

['111000111000' '101001110000']
['110111101110' '101011010110']
['111011011110' '110001011011']
['1000100101001' '111100111110']
['1010010011011' '1001100111001']
['1010011101100' '1001111110100']
['1000011110100' '1000000101000']
['111000011100' '110100010111']
['110001011100' '101011101101']
['100011001111' '011100001011']
['001101110101' '000100011101']
['110001010110' '100111010001']
['1001001001111' '10111111100111']
['10011010010100' '10001111111001']
['101101110101100' '101100011100100']
['101000110100001' '100111010110111']
['100100111001100' '100011011001011']
['100001110111101' '100000011000110']
['1011111010100000' '1011101111100000']
['1011101011011011' '1011100010010101']
['1011101001110000' '1011100011001000']
['1011111010100011' '1011110110001101']
['100010100001101' '100010000011100']
['100110000011101' '100101011111101']
['101000011100100' '100111110110111']
['101010110001001' '101010010011010']
['101101111110111' '101101100111011']
['10000101101000' '10000011100000']


['1010101101101' '1000001110001']
['10000010010111' '1100000010110']
['10100010110011' '1110011001001']
['11000011011100' '10001001001110']
['11100110110100' '10100011111110']
['11110100100100' '10101100100100']
['11101000000001' '10011111100001']
['11011011101000' '10010100011000']
['11001001100001' '10000100011111']
['10100110111001' '1101000000011']
['10000101111101' '1010000001111']
['1101100100010' '1000001101011']
['1010111010111' '110110101101']
['1000000001101' '100110011100']
['101101001000' '011011111110']
['101000101011' '011101111000']
['110011100111' '101001100010']
['1001111100100' '1000100111011']
['1100111111100' '1011101100111']
['1111000001100' '1101001110110']
['10001001111110' '1110010110011']
['10001101110000' '1110001111110']
['1111001100100' '1011101100111']
['1011011101001' '111100110001']
['1000001100011' '011111111000']
['010111010100' '110111101001']
['1011000110011' '10111011101010']
['10100011101010' '10001001011111']
['101111010010111' '101100110011001']
[

['10010111111000' '10111100001011']
['1000111111001' '100111010010']
['110001101010' '001011010011']
['010111100001' '101100010010']
['111101000111' '1010000000011']
['1011100100100' '1110000000010']
['1110001111111' '10000011010011']
['1110010101101' '10000011111111']
['1011111111001' '1110100101100']
['1011011100100' '1101110011010']
['1100111011001' '1110101110100']
['1110000001011' '1111001110101']
['1111010100100' '10000000001111']
['1111101111010' '10001010110110']
['10000101110010' '10011001011010']
['10011010101101' '10101011101000']
['10100111011111' '10110111000011']
['10111100011101' '11001001100001']
['11011011110010' '11101000111001']
['11110001101000' '100000111010011']
['11111111100101' '100011100111101']
['100000111100110' '100101011101000']
['100000100100001' '100110010011001']
['11110011001001' '100101001111111']
['11011010101100' '100011000000111']
['11001011101101' '100001100011111']
['11001010111101' '100001110110000']
['10111110101001' '100001011100100']
['1010001

['1000111101101' '1001010010110']
['1011110000111' '1011100001010']
['110011000111' '101100101011']
['000101001001' '111100101100']
['011010010110' '001111010101']
['110100111000' '100100100000']
['1001011000110' '110101011001']
['1010011101000' '110111001100']
['1001101011101' '101101001110']
['1000001110001' '011111010101']
['110111001001' '010001010101']
['101111000111' '000101100110']
['100011011000' '110101100000']
['010001111111' '100010101100']
['000100011100' '1010010011101']
['111100000010' '1000100100001']
['110100000101' '10110101000011']
['101001110100' '10100101001110']
['100101110010' '10011011101000']
['101011001101' '10011011001010']
['111001110011' '10100100001001']
['001001011000' '10101110101001']
['011000010100' '1000000010100']
['100101000010' '1010010010111']
['110010010011' '100010000011']
['111010011011' '101101000111']
['110000111100' '101010011011']
['100001011010' '100100110011']
['010100110101' '100010010100']
['001110010000' '100011111110']
['001000000001' 

['101100000101100' '10001100101010']
['101101000000100' '10001111100100']
['101110000011100' '10010011111110']
['101111101110111' '10011101101001']
['10001100101001' '10101000010111']
['10010101010001' '10101100111100']
['10011111010001' '10110010110110']
['10101111111101' '10111111010010']
['10111110001011' '1001000111110']
['1001001010101' '1010000011101']
['1011001110011' '1011101001010']
['101101001101' '101011110110']
['000000000000' '111001011011']
['001100100100' '000010010111']
['010111110110' '001010110100']
['101000100100' '010111111100']
['111001100100' '100101110001']
['1001000101011' '110011001111']
['1010110100000' '111111111111']
['1100100101110' '1001101100001']
['1110010101110' '1011100001101']
['10000000001010' '1101010011110']
['10010000001111' '1111011100011']
['10100000001101' '10001101100010']
['10101111000100' '10011111101101']
['10111010110100' '10101111101011']
['11000001001100' '10111010101100']
['11000110011010' '11000101111001']
['11010000100001' '1101010011

['10100001100011' '10000100011001']
['10011111011000' '10000001011101']
['10011101110111' '101111111100010']
['10011011110110' '101111101010110']
['10010111011001' '101111001011101']
['10001111000001' '101110001110001']
['10001000000111' '101101010100111']
['10000110000000' '101101000010010']
['10000101010011' '101101000100011']
['101111110111110' '101100100000111']
['101110011010110' '101011001100010']
['101101000001001' '101001111110110']
['101011111110011' '101001001000011']
['101011010010110' '101000100101011']
['101010111100010' '101000010110111']
['101010111101010' '101000011101011']
['101010101001111' '101000010111110']
['101001111001001' '100111101111000']
['101001101100101' '100111100100011']
['101010100111001' '101000100011110']
['101100001100000' '101010001111000']
['101101100010011' '101011110001011']
['101110100011001' '101100111100110']
['101111100100101' '101110001101101']
['10000100100100' '101111100000110']
['10001101110101' '10001000000001']
['10011100000010' '1001100

['001001011001' '001110011000']
['000000001001' '001001011010']
['111001000100' '000101101001']
['111000000100' '000110101011']
['110111100100' '001000011001']
['110100010110' '000111011011']
['110010010111' '000110110110']
['110010011000' '000111101010']
['110001111111' '000111110010']
['110100110101' '001010100010']
['111110101001' '010010111101']
['001001110000' '011100111101']
['001111011001' '100011000101']
['010010110110' '100111111101']
['011001000010' '101111010101']
['100000001101' '110110111010']
['100101111001' '111101000011']
['101010001000' '1000010010000']
['101100000100' '1000101001111']
['101000110001' '1000011100011']
['100001110111' '111110011100']
['011100111111' '111010100100']
['011011000000' '110111110010']
['011000011001' '110010111010']
['010011100001' '101100001101']
['001110111101' '100101100001']
['001100000011' '100000010110']
['001001110010' '011011010101']
['001010000011' '010111100101']
['001110110111' '010110111100']
['010100111101' '010111101001']
['011

['101000101101' '101111100011']
['101011010010' '110001000011']
['101101110101' '110010100011']
['101111100011' '110011011011']
['110000011010' '110011011001']
['110000100001' '110011001000']
['110000001000' '110010100011']
['101111010101' '110001100010']
['101110000001' '101111111001']
['101100100101' '101110001010']
['101011011110' '101100110000']
['101001110100' '101010101001']
['100111111001' '101000000100']
['100110100000' '100110000001']
['100101100111' '100100000111']
['100100001001' '100001111001']
['100010110011' '011111110010']
['100001111001' '011101111100']
['100000101110' '011011101101']
['011111011110' '011001100000']
['011110110111' '010111111110']
['011110000011' '010110010101']
['011100111100' '010100011111']
['011011101011' '010010110101']
['011010000100' '010000110111']
['010111110011' '001110000111']
['010101111011' '001011100101']
['010100100101' '001001110001']
['010011010000' '001000000111']
['010001101111' '000110001011']
['010000010110' '000100001101']
['001110

['001010101010' '000111100010']
['001010010111' '000110010011']
['001001111001' '000101001101']
['001001110001' '000100011101']
['001001011010' '000011011111']
['001000101010' '000010001000']
['000111111100' '000001001110']
['000111100001' '000000110100']
['000110110111' '111111111100']
['000110011000' '111111000001']
['000110010110' '111110110001']
['000101111100' '111110100001']
['000100001110' '111101010011']
['000010000000' '111011110011']
['000000100001' '111010110101']
['111111100111' '111010010101']
['111110011111' '111001011001']
['111100111000' '110111111011']
['111011100100' '110110110001']
['111010011011' '110110010101']
['111001000110' '110110000101']
['110111101000' '110101101110']
['110110011010' '110101100100']
['110101010101' '110101011011']
['110100011000' '110101000000']
['110011011110' '110100101101']
['110010110010' '110100011000']
['110010000111' '110100000010']
['110001100000' '110011011100']
['110001000001' '110010111001']
['110000011110' '110010100100']
['101111

['111101100011' '111100011101']
['111101111110' '111100111011']
['111101111010' '111101000000']
['111101011011' '111100101111']
['111101001111' '111100101111']
['111101001111' '111101000000']
['111100111010' '111100111000']
['111100101110' '111100011001']
['111100110100' '111100001010']
['111101000110' '111100010011']
['111101001100' '111100010110']
['111100111010' '111100001100']
['111100011111' '111100000011']
['111100010100' '111100000010']
['111100011110' '111100001111']
['111100101101' '111100011101']
['111101000010' '111100111011']
['111101011110' '111101101001']
['111101110110' '111110001110']
['111101111111' '111110011101']
['111101110101' '111110100101']
['111101111011' '111111000000']
['111110100010' '111111101110']
['111111000111' '000000001111']
['111111010011' '000000100010']
['111111101101' '000000111110']
['000000010010' '000001101101']
['000000101101' '000010010011']
['000000111001' '000010100010']
['000001000100' '000010110110']
['000001100001' '000011100001']
['000010

['111001100100' '111100110111']
['111001010110' '111100101101']
['111001010010' '111100101000']
['111001010010' '111100100011']
['111001010001' '111100100000']
['111001100011' '111100101100']
['111010000001' '111100111000']
['111010011011' '111101001010']
['111010111110' '111101011101']
['111011010101' '111101101011']
['111011101010' '111101110110']
['111100000111' '111110001010']
['111100100101' '111110011011']
['111101001111' '111110100111']
['111101110110' '111110110100']
['111110011101' '111111001100']
['111111000010' '111111011101']
['111111101011' '111111110101']
['000000011010' '000000010100']
['000001000010' '000000101101']
['000001101001' '000001000000']
['000010001011' '000001010001']
['000010101110' '000001100011']
['000011011000' '000010000010']
['000100000100' '000010011110']
['000100101000' '000010110000']
['000101001000' '000010111111']
['000101011011' '000011001001']
['000101101010' '000011011011']
['000101110100' '000011100110']
['000110000010' '000011101111']
['000110

['000011100111' '000000110100']
['000011100001' '000000110011']
['000011010110' '000000100101']
['000011000101' '000000010101']
['000010110010' '000000001000']
['000010100100' '111111111010']
['000010011000' '111111110010']
['000010010000' '111111110010']
['000010001100' '111111110110']
['000001111111' '111111111111']
['000001101011' '000000000011']
['000001010111' '000000000100']
['000001001011' '000000001011']
['000000111100' '000000001100']
['000000100110' '000000000011']
['000000001100' '111111111001']
['111111101110' '111111110000']
['111111011101' '111111100111']
['111111001100' '111111100001']
['111110111000' '111111011000']
['111110100100' '111111001111']
['111110010010' '111111001011']
['111110000000' '111111000010']
['111101100111' '111110111001']
['111101011001' '111110110111']
['111101001101' '111110111001']
['111101000010' '111110111001']
['111100101100' '111110110001']
['111100011010' '111110101001']
['111100001010' '111110100011']
['111100000011' '111110011011']
['111011

In [75]:

#  [  [                     ]  , [                       ] ]

In [76]:
hello = np.random.uniform(-1, 1, fs)
print(hello)

len(hello)

[0.79902664 0.0602312  0.50566486 ... 0.21442052 0.19737067 0.25236788]


44100

In [77]:
scaled = np.int16(hello / np.max(np.abs(hello)) * 32767)
print(scaled)
len(scaled)

[26181  1973 16569 ...  7025  6467  8269]


44100

In [84]:
sd.play(data)

In [60]:
sf.write('sound.wav', data, fs )